// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4taodpKyludcxLWfA76ejVvWe7gTp3hY',
    appId: '1:764771508054:android:1e184fd5acbc3dddb4c0f7',
    messagingSenderId: '764771508054',
    projectId: 'ami-style',
    storageBucket: 'ami-style.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo04zrgYfi2dF1lsbaZu-QA9GfP_yhhYs',
    appId: '1:764771508054:ios:292e4f57d0c5ed7fb4c0f7',
    messagingSenderId: '764771508054',
    projectId: 'ami-style',
    storageBucket: 'ami-style.firebasestorage.app',
    androidClientId: '764771508054-66k1jkb73opgdempo8jm5lj0ft17uc26.apps.googleusercontent.com',
    iosBundleId: 'jp.amiplus.lisa',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeTWm-abEMd6vB9OdiiYyfNqnrjmysQjk',
    appId: '1:764771508054:web:57956be7f3a05061b4c0f7',
    messagingSenderId: '764771508054',
    projectId: 'ami-style',
    authDomain: 'ami-style.firebaseapp.com',
    storageBucket: 'ami-style.firebasestorage.app',
    measurementId: 'G-53GZL7Z3V2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo04zrgYfi2dF1lsbaZu-QA9GfP_yhhYs',
    appId: '1:764771508054:ios:e20956b073daa490b4c0f7',
    messagingSenderId: '764771508054',
    projectId: 'ami-style',
    storageBucket: 'ami-style.firebasestorage.app',
    androidClientId: '764771508054-66k1jkb73opgdempo8jm5lj0ft17uc26.apps.googleusercontent.com',
    iosBundleId: 'jp.amiplus.amiapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeTWm-abEMd6vB9OdiiYyfNqnrjmysQjk',
    appId: '1:764771508054:web:d58a98d19b57536eb4c0f7',
    messagingSenderId: '764771508054',
    projectId: 'ami-style',
    authDomain: 'ami-style.firebaseapp.com',
    storageBucket: 'ami-style.firebasestorage.app',
    measurementId: 'G-ETN8XGFH10',
  );

}