// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS0SggiaEB61WiKbI20nbI7k5ZsnV0_XM',
    appId: '1:871225930361:android:9b389be51eb68acf931aa8',
    messagingSenderId: '871225930361',
    projectId: 'frinurse',
    databaseURL: 'https://frinurse.firebaseio.com',
    storageBucket: 'frinurse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXGE0Z1cKJa3hJ8CyKAadd28dcFcVCWOI',
    appId: '1:871225930361:ios:6a7bdcab4502722c931aa8',
    messagingSenderId: '871225930361',
    projectId: 'frinurse',
    databaseURL: 'https://frinurse.firebaseio.com',
    storageBucket: 'frinurse.appspot.com',
    androidClientId: '871225930361-b4au5v3tkjqmgrencu5p2e2lkeutsfhr.apps.googleusercontent.com',
    iosClientId: '871225930361-f53prj32qpg3nomdt2ou0bp1hgbgtti4.apps.googleusercontent.com',
    iosBundleId: 'jp.dell-inc.so.test',
  );
}
